spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://cdb-fmybdjyc.cd.tencentcdb.com:10118/esg?useUnicode=true&characterEncoding=utf8
    username: root
    password: esgzhuanyeshixi2020
  #redis配置
  redis:
    port: 6379
    host: 47.103.203.188
    lettuce:
      pool:
        max-active: 8 #连接池最大连接数
        max-idle: 8   #连接池最大空闲连接
        min-idle: 0   #连接池最小空闲连接
        max-wait: 1000 #最大阻塞等待时间
    password: redis


#端口配置
server:
  port: 4396

#mybatis版本问题,不加这个不会自动扫描包
mybatis:
  type-aliases-package: com.tongji


